apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: netlifytrial-igqt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pshivpuj-tenant/my-app-3/netlifytrial-igqt@sha256:7fb7adcde1e9b816a9162f0653caef6da3a31696fc1cb62820a8fe91c779c4d9
        name: my-nodejs
        resources: {}
status: {}
