apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-igqt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-igqt
    app.kubernetes.io/part-of: my-app-3
  name: netlifytrial-igqt4hti
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: netlifytrial-igqt
    weight: null
status: {}
