apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial-igqt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial-igqt
    app.kubernetes.io/part-of: my-app-3
  name: netlifytrial-igqt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: netlifytrial-igqt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: netlifytrial-igqt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pshivpuj-tenant/my-app-3/netlifytrial-igqt@sha256:7fb7adcde1e9b816a9162f0653caef6da3a31696fc1cb62820a8fe91c779c4d9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
